### ISSUE TITLE
Print out the alpha parameters

### ISSUE THREAD

**Issue by sshen82** [canzarlab/JVis-learn#3]
Hi, thank you for your great software! Right now everything is great, but could you please add in the alpha which is the weight parameters for the output? I want to look at which data input is more important.

**Comment by vanhoan310** [comment]
Dear sshen82,

thank you for using JVis. Here is how to print the weight for parameters

For j-SNE:
data = {'rna': expr_reduced, 'chromatin': atac_reduced, 'noise': noise_matrix}
jsne_obj = JTSNE(init='random')
# _lambda is the lambda parameter in our paper. We suggest to use _lambda from 1 to 3 for j-SNE.
joint_tsne = jsne_obj.fit_transform(X = data, method = 'auto', _lambda = 3) 
# print alpha: the weight of modalities is same order as the data (for this example: rna, chromatin, noise)
print(jsne_obj.alpha)

For j-UMAP
jumap_obj = JUMAP(init='random')
# ld is lambda parameter in our paper. Try ld from 0.5 to 3 for j-UMAP.
joint_umap = jumap_obj.fit_transform(X = data, method = 'auto', ld = 1, max_iter = 10)
# print alpha
print(jumap_obj.alpha)

If you don't specify lambda in the function fit_transform, by default we use the uniform weight.

You can find more in our examples here:
https://github.com/canzarlab/JVis_paper/tree/master/proof_of_principle

Please let me know if you have any question.
