### ISSUE TITLE
Could I run JVis-learn on GPU?

### ISSUE THREAD

**Issue by yulijia** [canzarlab/JVis-learn#4]
Hi, 
I noticed this package uses `numba`; can `JVis-learn` be executed on a GPU?
It used all the cores of my server for running the small demo on the README page.

Many thanks,
Lijia

**Comment by vanhoan310** [comment]
Dear Lijia,

Thank you for your questions and interest in using our package. If you don’t wish to use all the cores at once you can restrict the number of threads that numba uses by making use of the environment variable NUMBA_NUM_THREADS; see the [numba documentation](https://numba.pydata.org/numba-doc/dev/reference/envvars.html#threading-control) for more details.

If you run j-SNE, you can set the number of cores as follows:
https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html

Currently we don't support GPU. In the future it is possible that GPU support may be added.

**Comment by yulijia** [comment]
Hi @vanhoan310,

Thank you for your reply!
Hope in the future JVis-learn will have a GPU support to processing large datasets!
